name: plant_disease_detection
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  image: ^3.0.2
  image_picker: ^1.1.1
  lottie: ^3.1.0
  path_provider: ^2.1.3
  quiver: ^3.2.1
  speech_to_text: ^6.6.1
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  tflite_flutter: ^0.9.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  stacked_generator: ^1.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/svg/
    - assets/labels.txt
    - assets/model_unquant.tflite

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/Euclid Circular A Regular.ttf
